### ISSUE TITLE
Doubly-braced fields in sources.bib parsing

### ISSUE THREAD

**Issue by chrzyki** [SimonGreenhill/rcldf#1]
Library works really well, thank you! One thing I noticed with curly braces in BibTeX:

```r
df <- cldf("yanglalo/cldf")
df[["sources"]][["TYPE"]]
```

reports `"PhD} dissertation"`. The `type` in the sources.bib is `type = {{PhD} dissertation}`.

**Comment by SimonGreenhill** [comment]
Hmm.. that must be a glitch in `bib2df`. I'll look into it.

**Comment by SimonGreenhill** [comment]
Pushed upstream: https://github.com/ropensci/bib2df/issues/30
