### ISSUE TITLE
Are the keys of "tables" the stems of the corresponding filenames or CLDF component names?

### ISSUE THREAD

**Issue by shh-dlce-zenodo** [SimonGreenhill/rcldf#10]
It seems that the library doesn't make use of / respect the `dc:conformsTo` specs, marking tables as CLDF components. Thus it relies on filenames as interface, when CLDF provides an abstraction mechanism to redirect component names to filenames.

**Comment by SimonGreenhill** [comment]
Fixed in #a480028
