### ISSUE TITLE
Consult/respect CSV dialect spec when reading tables

### ISSUE THREAD

**Issue by xrotwang** [SimonGreenhill/rcldf#18]
Currently it seems the default CSV dialect for CLDF datasets is baked in as only option.
https://github.com/SimonGreenhill/rcldf/blob/51e467fc5f155607f900e331f589a2a4da1550ad/R/rcldf.R#L47

**Comment by HedvigS** [comment]
@xrotwang are there any limits in CLDF on what kinds of things we could expect as delims and quotes? Is any CSV-dialect okay, or are there certain restrictions somewhere?

**Comment by HedvigS** [comment]
@xrotwang how is this handled currently in pycldf? I'm browsing different approaches to this problem in R and if possible i'd like to not reinvent the wheel.

There's no where in the JSON this is specified is there?

**Comment by xrotwang** [comment]
CSV dialect specs are defined in the CSVW standard, see https://w3c.github.io/csvw/metadata/#dialect-descriptions
The only thing CLDF adds to that is that it specifies a default CSV dialect in case no specific description is found in a dataset's JSON metadata, see https://github.com/cldf/cldf#metadata-free-conformance

**Comment by xrotwang** [comment]
Since CSV dialects are specified in CSVW, the implementation is in the `csvw` package, see
https://github.com/cldf/csvw/blob/master/src/csvw/dsv_dialects.py

So maybe this should be mimicked in the R world, implementing support for CSV dialects in https://github.com/Robsteranium/csvwr rather than in rcldf?

**Comment by xrotwang** [comment]
A bit more detail on how `csvw` handles CSV dialects:
https://github.com/cldf/csvw/blob/fa8b9e696f08ee1f5429294772ad0dabe932729f/src/csvw/dsv.py#L145-L191

Most of the attributes of a CSV dialect are understood by python's `csv` reader, see https://docs.python.org/3/library/csv.html#csv-fmt-params
Some attributes require tweaking what the default CSV reader does, see https://github.com/cldf/csvw/blob/fa8b9e696f08ee1f5429294772ad0dabe932729f/src/csvw/dsv.py#L201-L217

**Comment by xrotwang** [comment]
Since CSV dialect-aware parsing can get somewhat complicated - and considering that almost all `cldfbench` created CLDF datasets will use the default dialect - it may be a good first step to simply check whether a dataset sticks to the default and raise an error if not. For the default, `csvwr` will work.

**Comment by xrotwang** [comment]
https://doi.org/10.5281/zenodo.7135691 uses tabstops as delimiter, hence, the metadata contains:
```json
   "dialect": {"delimiter": "\t"},
```

**Comment by xrotwang** [comment]
The CVSW test suite contains a lot more such cases, e.g. https://w3c.github.io/csvw/tests/#manifest-json#test023
Just search the JSON tests for "dialect".

**Comment by HedvigS** [comment]
Ah, so dialect in that CLDF-json means csvw-dialect always. That should be easy to check for.

**Comment by xrotwang** [comment]
Yes, [dialect](https://www.w3.org/ns/csvw#class-definitions) is a term from the CSVW namespace. The CLDF metadata JSON file is in JSON-LD - i.e. it's a serialized RDF graph, so each property is either a URL or comes from a known namespace.

**Comment by HedvigS** [comment]
> @SimonGreenhill @HedvigS it should be noted that csvwr doesn't really support dialect specs at the moment (see https://github.com/Robsteranium/csvwr/blob/c4b6264b372108675225e09a09452c7eb7127bd6/R/csvwr.R#L227-L231). It only handles the `headerRowCount` property but **not** more important ones like `delimiter` or `quoteChar`. So this issue is closed pending a solution in csvwr.

Got it. Well, it seems likely that they'll develop a solution (or we could contribute to a solution over there). It feels good to not reinvent the wheel in several places.
