### ISSUE TITLE
adding reduce_to_language

### ISSUE THREAD

**Issue by HedvigS** [SimonGreenhill/rcldf#25]
@SimonGreenhill would you be open to adding a function to this package that takes a table, checks if it has glottocodes and if so reduces to only language or family glottocodes, i.e. prunes off dialects?

We could give people options: random dropping, dropping based on data coverage or dropping based on specific vector.
[
See also this issue for similar task.](https://github.com/SietzeN/glottospace/issues/54)

If you are open to this Simon, I could try my hand at making said function and make a PR to this repos.

**Comment by xrotwang** [comment]
In the CLDF context

> checks if it has glottocodes

basically means, "take the `LanguageTable`", because that's where [glottocode](https://cldf.clld.org/v1.0/terms.html#glottocode) columns have a defined role.

Also, this function would need access to Glottolog data. Is this supposed to be passed in? To me, it would feel a bit backwards, if the caller has
- access to `LanguageTable`
- access to the required Glottolog data

but then passes this into a function in `rcldf` to get dialects thrown out. Wouldn't a suitable join of `LanguageTable` and a suitably filtered `LanguageTable` of `glottolog-cldf` do the trick?

**Comment by HedvigS** [comment]
A suitable join of LanguageTable and glottolog-cldf is precisely what needs to be done. Currently, several of our collaborators are unfamiliar with doing this and are using the grambank-analysed scripts to do this. This is also relevant for trees. You said Robert that functions of this kind of generality would be a good idea to put into a package instead of [just in a script if they are used multiple times.](https://github.com/grambank/grambank-analysed/blob/08f3c7a8269cfafc6fe23e3a52edd6d2a4faee0e/R_grambank/make_wide.R#L65) It seemed to me that rcldf would be one possible location for such a function. Did I misunderstand what you meant?

The function could have arguments for how to pick among duplicates (random, by data coverage, by specific list) and an argument for if the outcome is a df subsetted or a vector of subsetted ids that could be passed to ape::keep.tip() in case of pruning phylogenies.

**Comment by xrotwang** [comment]
I think functionality that needs to know about the semantics in glottolog-cldf - i.e. know what's a dialect and what not - would belong into `rglottolog` or similar, but not into a generic CLDF package like `rcldf`. But then, Glottolog as provider of language metadata is somewhat baked into CLDF, so maybe the functionality could go here.

It's a a bit counterproductive that the overhead incurred by getting a package into CRAN is so high that putting functionality into small, focused packages seems to be a no-go quite often.

**Comment by HedvigS** [comment]
Personally I think that CLDF for language data-sets relies so much on glottolog that this isn't that odd to expect to need to fetch glottolog-cldf. It's already the case for [glottotrees](https://github.com/erichround/glottoTrees/commit/a1090c893bca8f8f05d56cdf4abe13376d6610d4) and [glottospace](https://github.com/SietzeN/glottospace/blob/main/R/glottoget_glottolog.R) for example.

I'm not really sure what you mean. I'm just trying to get by here. I've written scripts for the analysis we need to do at grambank-analysed, and I want as many readers and collaborators of ours to easily run and understand what's going on. 
 In my experience, that's best achieved by not requiring complex installs (i.e. using only R or only python) and sharing scripts and trying to make those scripts as understandable as possible. When I read other people's papers, I look at their scripts. I rarely read papers where the code is baked into a package. Usually, it's just in plain scripts, sometimes even poorly commented scripts :). I guess people don't make packages more because like me, they're pressed for time and resources and it's an achievement that usually doesn't get much appreciation by career advancement. In addition, making packages should include robust testing and a possibility for committed maintenance - which is not something everyone is able to commit to.

**Comment by SimonGreenhill** [comment]
This seems like something outside the scope of rcldf -- it's very much a grambank problem. Perhaps there should be an gRambank package that wraps up this sort of functionality.

**Comment by HedvigS** [comment]
Okay. I thought it was relevant for other cldf-datasets, like D-PLACE etc but sure. We'll work something else out, or I'll just continue with the scripts as before.

**Comment by xrotwang** [comment]
Maybe something like `grambankr` wouldn't be a bad idea. At least without [submisson to CRAN](https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/r-package/#section6)  the process doesn't seem [overly complicated](https://tinyheero.github.io/jekyll/update/2015/07/26/making-your-first-R-package.html).

**Comment by xrotwang** [comment]
> packages should include robust testing and a possibility for committed maintenance

I think once functionality is properly packaged, it becomes a lot easier to
- collaborate on it (thus opening up a way for others to contribute tests)
- pass it on to new maintainers.

**Comment by HedvigS** [comment]
Okay. I'd be open to this, if there is support. I'm a bit unsure of the value, seems a bit like it'd be very few functions but maybe that's fine.

**Comment by xrotwang** [comment]
Yes, that's fine. The value is big. I think the opening paragraphs of https://tinyheero.github.io/jekyll/update/2015/07/26/making-your-first-R-package.html sum this up quite well. I'd also say that being able to package code properly means entering a new level of coding. It's the level where thinking about modularization, maintenance, testing etc. starts to make sense. And considering that the average analysis project lasts months to years, thinking about these things pays off.

**Comment by HedvigS** [comment]
@xrotwang Okay. 

I'd need to clear that with Russell first before starting. I'll add it to the GB papers meetings agenda

**Comment by HedvigS** [comment]
to be clear, i see no value in replicating tidyverse or other package functions with just some specifics to grambank. i'd only focus on what we do in grambank code repeatedly that is not easily done with robust already existing functions.

**Comment by xrotwang** [comment]
Yes, that seems like a good start. From my experience, once you have a place to put code, even moving one-liners there, just because it allows for documentation and testing, starts to be a reasonable option.
