### ISSUE TITLE
replace is_url with  RCurl::url.exists

### ISSUE THREAD

**Issue by HedvigS** [SimonGreenhill/rcldf#36]
I saw Simon had commented that maybe the current version of` is_url() `is to simplistic. 

One alternative could be  `RCurl::url.exists()`

**Comment by SimonGreenhill** [comment]
These are quite different semantically. is_url just checks if the string looks like a url. RCurl::url.exists asks for a network resource to check if it exists. 

Switching to url.exists would mean that rcldf would not be able to load a CLDF dataset without an active network connection.

**Comment by HedvigS** [comment]
> These are quite different semantically. is_url just checks if the string looks like a url. RCurl::url.exists asks for a network resource to check if it exists.
> Indeed, they're not identical.


> Switching to url.exists would mean that rcldf would not be able to load a CLDF dataset without an active network connection.

Right, that's on disadvantage sure. I just wanted to offer you a potential solution since I saw that you had written a comment that the current set-up was too simplistic.
