### ISSUE TITLE
as.cldf.wide Hack rlang::`:=`

### ISSUE THREAD

**Issue by Fixsme** [SimonGreenhill/rcldf#4]
Dear Dr. Greenhill,

I saw your post on twitter about getting feedback on your package. I'm getting back on the `as.cldf.wide` function. In order to get the R CMD check compile with no warning, you needed to use the following syntax:

```{r}
`:=` <- rlang::`:=`
```
Have you tried using the following code in the documentation of the function ?
```{r}
#' @import rlang
```
When read by roxygenize(), this line should write an entry in the NAMESPACE in order to  import the rlang package in the environment of the package.

It is good practice to list in the documentation of the function all the packages needed for that function to work with "@import <pckg>" or "@importFrom <pckg> <function>".

I hope this feedback will be of any use.

Sincerely,

François-Xavier Toledo

**Comment by SimonGreenhill** [comment]
Thanks @Fixsme -- sorry, I just saw this now, the notification must have slipped by somehow. You would have saved me a few hours! Oh well, I think it's fixed now, thanks anyway!
