### ISSUE TITLE
? values

### ISSUE THREAD

**Issue by HedvigS** [SimonGreenhill/rcldf#45]
It seems like rcldf::cldf turns `?`-values to missing as default. I suspect that this has to do with the CodeTable, because for example for Grambank "?" isn't listed as a possible code for any parameter but it is still available as a possible Value for every Parameter in the ValueTable.

Maybe you could either
a) write in the documentation of rcldf::cldf that values not found in CodeTable will be treated as missing, e.g. as with `?`-values in Grambank
b) adjust the function to optionally allow `?` values  in the resulting ValueTable

I don't know of other similar situations in other CLDF-dataests of values that occur in the ValueTable but not in the CodeTable. I hope that it's usually `?` but I don't know.

Examples below of different results depending on using rcldf or not.

```

> library(tidyverse)
> install_github("SimonGreenhill/rcldf", dependencies = TRUE,  ref = "v1.2.0")
> library("rcldf")  
> cldf_grambank <- rcldf::cldf("https://zenodo.org/records/7844558/files/grambank/grambank-v1.0.3.zip", load_bib = F)
Reusing cache in: /Users/skirgard/Library/Caches/org.R-project.R/R/rcldf/91ccd4d65c819ecf9d131d5760a6d48b
>                                                                                                                                                                      
> cldf_grambank$tables$ValueTable %>% 
+   filter(Language_ID == "abad1241") %>% 
+   filter(Parameter_ID == "GB020")
# A tibble: 1 × 9
  ID             Language_ID Parameter_ID Value Code_ID Comment                                         Source Source_comment Coders
  <chr>          <chr>       <chr>        <chr> <chr>   <chr>                                           <chr>  <chr>          <chr> 
1 GB020-abad1241 abad1241    GB020        NA    NA      Author states there is a possible example of a… s_OaP… Oa & Paul 201… JLA   
> 
> ValueTable_not_rcldf <- read_csv("https://raw.githubusercontent.com/grambank/grambank/v1.0.3/cldf/values.csv", show_col_types = F)  
>                                                                                                                                 
> ValueTable_not_rcldf %>% 
+   filter(Language_ID == "abad1241") %>% 
+   filter(Parameter_ID == "GB020")
# A tibble: 1 × 9
  ID             Language_ID Parameter_ID Value Code_ID Comment                                         Source Source_comment Coders
  <chr>          <chr>       <chr>        <chr> <chr>   <chr>                                           <chr>  <chr>          <chr> 
1 GB020-abad1241 abad1241    GB020        ?     NA      Author states there is a possible example of a… s_OaP… Oa & Paul 201… JLA  
```

**Comment by johenglisch** [comment]
The Grambank cldf data set specifies `?` as the designated *null* value:

https://github.com/grambank/grambank/blob/cb9adc433f7a4294d3f64569f91004b8a379ee58/cldf/StructureDataset-metadata.json#L86-L88

So, afaict rcldf is just conforming to the standard here.

Also, it seems we set this *null* value on purpose, though I don't remember why:

https://github.com/grambank/grambank/blob/cb9adc433f7a4294d3f64569f91004b8a379ee58/cldfbench_grambank.py#L108

**Comment by HedvigS** [comment]
> The Grambank cldf data set specifies `?` as the designated _null_ value:
> 
> https://github.com/grambank/grambank/blob/cb9adc433f7a4294d3f64569f91004b8a379ee58/cldf/StructureDataset-metadata.json#L86-L88
> 
> So, afaict rcldf is just conforming to the standard here.
> 
> Also, it seems we set this _null_ value on purpose, though I don't remember why:
> 
> https://github.com/grambank/grambank/blob/cb9adc433f7a4294d3f64569f91004b8a379ee58/cldfbench_grambank.py#L108
> 
> _Update:_ btw, I had a quick look at the web app. When it loads the cldf data it [treats any missing value as `?`](https://github.com/clld/grambank/blob/65eba56de16d882c6cf635b0ae95df3d3a65752b/grambank/scripts/initializedb.py#L265) and manually [adds codes](https://github.com/clld/grambank/blob/65eba56de16d882c6cf635b0ae95df3d3a65752b/grambank/scripts/initializedb.py#L110) for the `?` values. So, that's how they show up again.

Thank you @johenglisch !

So, we're meant to tell apart missing from NULL in this case by there now being a row in the ValueTable or there being a row with a null value?

**Comment by johenglisch** [comment]
Yes, existing row with `NA` as its value means `?`; non-existing row means missing.

**Comment by HedvigS** [comment]
(Thanks again @johenglisch for this, I encountered the same confusion today and thought "hm I seem to recall someone explained that to me" and found this issue ^^!)
