### ISSUE TITLE
Warning: `as_data_frame()` is deprecated as of tibble 2.0.0.    

### ISSUE THREAD

**Issue by SimonGreenhill** [SimonGreenhill/rcldf#7]
This is caused upstream by `bib2df`. It was fixed in https://github.com/ropensci/bib2df/commit/2f9678d6c356000b7633d94997eed8d71694db06 but that is not in a released version yet. Workaround by installing bib2df from github:

```r
devtools::install_github("ropensci/bib2df")
```

**Comment by HedvigS** [comment]
sorry, should have seen this when I opened #16
